spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver
    druid:
      filters: stat
      initial-size: 1
      maxWait: 60000
      minIdle: 1
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      max-active: 20
      time-between-connect-error-millis: 60000
mybatis:
    basepackage: com.yyq.**.mapper
    xmlLocation: classpath:sqlmapper/**/*.xml